server:
  port: 80

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: REGION-SERVICE
          uri: lb://REGION-SERVICE
          predicates:
            - Path=/api/v1/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${REGISTRY_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
