name: Release job
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Switch directories
        run: cd regionservice
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Print directories
          run: ls
      - name: Update Maven version
        run: mvn -B versions:set -DnewVersion=$(git describe --tags --abbrev=0) -DgenerateBackupPoms=false
      - name: Build with Maven
        run: mvn -B package --file pom.xml